app:
  name:
    spring-boot-modules
server:
  port: 1000
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    hikari:
      read-only: false
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 1800000
      maximum-pool-size: 60
      minimum-idle: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    elasticsearch:
      path:
        logs: ./elasticsearch/log #elasticsearch日志存储目录
        data: ./elasticsearch/data #elasticsearch数据存储目录

  session:
    store-type: redis
  #配置redis数据库连接
  redis:
    host: localhost
    port: 6379
    password:
    timeout: 3600 # 连接超时时间（毫秒）
    jedis:
      pool:
        max-idle: 20      # 连接池中的最大空闲连接
        min-idle: 1
        max-active: 20    # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 60000   #连接池最大阻塞等待时间
    database: 0   #默认是索引为的0的数据库
  mail:
    host: smtp.qq.com
    username: 51103942@qq.com
    #授权码g，在QQ邮箱客户端生成 修改成自己的  设置-账户-开启服务-获取授权码
    password: jtmoybnwknrnbjha
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
mybatis:
  type-aliases-package: com.example.dao.mapper
  mapper-locations: /mapper/*.xml