app:
  name:
    spring-boot-modules
server:
  port: 1000
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    hikari:
      read-only: false
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 1800000
      maximum-pool-size: 60
      minimum-idle: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.qq.com
    username: 51103942@qq.com
    #授权码g，在QQ邮箱客户端生成 修改成自己的  设置-账户-开启服务-获取授权码
    password: jtmoybnwknrnbjha
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


mybatis:
  type-aliases-package: com.example.dao.mapper
  mapper-locations: /mapper/*.xml